### ISSUE TITLE
HookLuaSetup.OnStartGame有可能会报错

### ISSUE THREAD

**Issue by qiuchangjie** [leinlin/Miku-LuaProfiler#23]
OnStartGame中的path对象有可能是null，建议改下
![图片](https://user-images.githubusercontent.com/5474239/95861719-6d990d80-0d94-11eb-9919-ec1d465746af.png)

**Comment by leinlin** [comment]
什么情况会为空啊

**Comment by leinlin** [comment]
最新的的搞了一个很奇葩的办法应该是解决了
